framework: torch

env: HalfCheetahPyBulletEnv-v0
horizon: 1000

num_gpus: 1.0
num_workers: 10
remote_worker_envs: True
num_envs_per_worker: 2
train_batch_size: 60000
sgd_minibatch_size: 4096
vf_clip_param: 200.0

lambda: 0.99
gamma: 0.95

# TUNED
kl_target: 0.01
clip_param: 0.2
lr_schedule: [[0, 0.0004], [10000000, 0.00004]]
kl_coeff: 1.0
# TUNED

model: 
    vf_share_layers: False
    fcnet_activation: relu
    free_log_std: True
    fcnet_hiddens: [64, 64]
